c_compiler:
  - gcc                      # [linux]
  - clang                    # [osx]
  - vs2019                   # [win]
cxx_compiler:
  - clangxx                  # [osx]
  - gxx                      # [linux]
  - vs2019                   # [win]

c_compiler_version:
  - 11                                 # [osx]
  - 9                                  # [linux]
cxx_compiler_version:
  - 11                                 # [osx]
  - 9                                  # [linux]
  
target_platform:
    - osx-64                           # [osx]
    - linux-64                         # [linux]
    - win-64                           # [win]